spring:
  application:
    name: admin-server
  security:
    user:
      password: "admin"
      name: "admin"
server:
  port: 18080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka